Library/Models/BookModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
	public class BookModel
	{
		[Key]
		public long Id { get; set; }
		[Required]
		[StringLength(100, MinimumLength = 3)]
		public required string Name { get; set; }
		[Required]
		[StringLength(100, MinimumLength = 3)]
		public required string Genre { get; set; }
		[Required]
		public required int Height { get; set; }
		[Required]
		public required int Width { get; set; }
		public long SetId { get; set; }
		public SetModel? Set { get; set; }
	}
}

Library/Models/ErrorViewModel.cs
namespace Library.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Library/Models/LibraryModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
	[Index(nameof(Genre), IsUnique = true)]
	public class LibraryModel
	{
		public long Id { get; set; }
		[Required,StringLength(100, MinimumLength = 3)]
		public required string Genre { get; set; }
		public List<ShelfModel> Shelfs { get; set; } = [];
	}
}

Library/Models/SetModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
	public class SetModel
	{
		public long Id { get; set; }
		[Required]
		[StringLength(100, MinimumLength = 3)]
		public required string Name { get; set; }
		public long ShelfId { get; set; }
		public ShelfModel? Shelf { get; set; }
		public List<BookModel> Books { get; set; } = [];
	}
}

Library/Models/ShelfModel.cs
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
	public class ShelfModel
	{
		public long Id { get; set; }
		[Required]
		public required int Height { get; set; }
		[Required]
		public required int Width { get; set; }
		public long LibraryId { get; set; }
		public LibraryModel? Library { get; set; }
		public List<SetModel> Sets { get; set; } = [];
	}
}

Library/Controllers/BookController.cs
using Library.Models;
using Library.Service;
using Library.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
	public class BookController : Controller
	{
		private readonly IBookService _bookService;
		public BookController(IBookService bookService)
		{
			_bookService = bookService;
		}

		public IActionResult Create(long id)
		{
			return View(new BookVM() { SetId = id });
		}

		[HttpPost]
		public IActionResult Create(BookVM bookVM)
		{
			BookModel book = _bookService.CreateBook(bookVM);
			long shelfId = _bookService.FindShelfIdBySetId(_bookService.FindSetById(book.Id));
			ShelfModel shelf = _bookService.FindShelfModelBySetId(shelfId);
			string error = "";
			if (book.Height <= shelf.Height)
				error = "Book is shorter then shelf";
			return RedirectToAction("Index","Set", new { id = _bookService.FindShelfIdBySetId(bookVM.SetId),error = error });
		}

		public IActionResult Delete(long id) 
		{
			long setId = _bookService.FindSetById(id);
			long shelfId = _bookService.FindShelfIdBySetId(setId);
			_bookService.DeleteBook(id);
			return RedirectToAction("Index","Set",new {id = shelfId});
		}
	}
}

Library/Controllers/HomeController.cs
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Library.Controllers
{
	public class HomeController : Controller
	{

		private readonly ILogger<HomeController> _logger;
		private readonly ApplicationDbContext _context;

		public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
		{
			_logger = logger;
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Library/Controllers/LibraryController.cs
using Library.Models;
using Library.Service;
using Library.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILibraryService _libryService;
        public LibraryController(ILibraryService libryService)
        {
            _libryService = libryService;
        }
        public IActionResult Index()
        {
            return View(_libryService.GetAllLibraries());
        }
        public IActionResult Details(long id)
        {
            LibraryModel? byId = _libryService.GetLibrariesById(id);

            if (byId == null) { return RedirectToAction("Index"); }

            return View(byId);
        }
        public IActionResult Create()
        {

            return View(new LibraryVM());
        }
        [HttpPost]
        public IActionResult Create(LibraryVM libary)
        {
            _libryService.CreateLibrary(libary);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(long id)
        {
            _libryService.DeleteLibrary(id);
            return RedirectToAction("Index");
        }
    }
}

Library/Controllers/SetController.cs
using Library.Models;
using Library.Service;
using Library.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class SetController : Controller
    {
        private readonly ISetService _setService;
        public SetController(ISetService setService)
        {
            _setService = setService;
        }
        public IActionResult Index(long id ,string error = "")
        {
            if(error != "")
                ViewBag.ErrorMessage = error;
            ViewBag.Id = id;
            return View(_setService.GetAllSetsById(id));
        }

        public IActionResult Create(long id)
        {
            var a = new SetVM() { ShelfId = id };
            return View(a);
        }
        [HttpPost]
        public IActionResult Create(SetVM set)
        {
            _setService.CreateSet(set);
            return RedirectToAction("Index", new { id = set.ShelfId });
        }
        public IActionResult Delete(long id)
        {
            var a = _setService.GetAllSetsByIdToDelete(id);
            var b = a[0].ShelfId;
              _setService.DeleteSet(id);
            return RedirectToAction("Index", new { id = b });
        }
    }
}

Library/Controllers/ShelfController.cs
using Library.Models;
using Library.Service;
using Library.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace Library.Controllers
{
    public class ShelfController : Controller
    {
        private readonly IShelfService _shelfService;
        public ShelfController(IShelfService shelfService)
        {
            _shelfService = shelfService;
        }
        public IActionResult Index(long id)
        {
            ViewBag.Id = id;
            return View(_shelfService.GetAllShelvesById(id));
        }

        public IActionResult Create(long id)
        {
            return View(new ShelfVM() { LibaryId = id });
        }

        [HttpPost]
        public IActionResult Create(ShelfVM shelf)
        {
            _shelfService.CreateShelf(shelf);
            return RedirectToAction("Index", new { id = shelf.LibaryId });
        }

        public IActionResult Delete(long ShelfId, long LibraryId)
        {
            _shelfService.DeleteShelfById(ShelfId);
            return RedirectToAction("Index", new { id = LibraryId });
        }

        public IActionResult Details(long id)
        {
            ShelfModel? byId = _shelfService.GetShelfById(id);

            if (byId == null) { return RedirectToAction("Index",new{ ViewBag.id}); }

            return View(byId);
        }

    }
}

Library/Views/Book/Create.cshtml
@model Library.ViewModel.BookVM

@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookVM</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Height" class="control-label"></label>
				<input asp-for="Height" class="form-control" />
				<span asp-validation-for="Height" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Width" class="control-label"></label>
				<input asp-for="Width" class="form-control" />
				<span asp-validation-for="Width" class="text-danger"></span>
			</div>
			<div class="form-group" hidden>
				<label asp-for="SetId" class="control-label"></label>
				<input asp-for="SetId" class="form-control" />
				<span asp-validation-for="SetId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Library/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Library/Views/Library/Create.cshtml
@model Library.ViewModel.LibraryVM
@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>
<h4>LibraryVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Library/Views/Library/Details.cshtml
@model Library.Models.LibraryModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LibraryModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        @foreach (var shelf in Model.Shelfs)
        {
            @if (shelf != null)
            {
                <h5>Shelf</h5>
                <h5>Height: @shelf.Height Width: @shelf.Width</h5>
            }
        }
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Library/Views/Library/Index.cshtml
@model IEnumerable<Library.Models.LibraryModel>

@{
	ViewData["Title"] = "Index";
}

<h1>Libreries</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Genre)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Genre)
				</td>
				<td>
					@Html.ActionLink("Shelf", "Index", "Shelf", new{id = item.Id}) |
					@Html.ActionLink("Details", "Details", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
			</tr>
		}
	</tbody>
</table>

Library/Views/Set/Create.cshtml
@model Library.ViewModel.SetVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SetVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ShelfId" class="control-label"></label>
                <input asp-for="ShelfId" class="form-control" />
                <span asp-validation-for="ShelfId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Set/Index.cshtml
@model IEnumerable<Library.Models.SetModel>

@{
	ViewData["Title"] = "Index";
}

<h1>Book Sets</h1>
@if (ViewBag.ErrorMessage != null)
{
	<span class="error-span" id="error" onclick="closeError()"> @ViewBag.ErrorMessage</span>
}
<p>
	@Html.ActionLink("Create New", "Create", "Set", new { id = ViewBag.Id })
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				Name
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					Set Name: @Html.DisplayFor(modelItem => item.Name)
					<hr />
					@foreach (var book in item.Books)
					{
						@if (book != null)
						{
							<h5>
								@book.Name |
								@Html.ActionLink("Delete", "Delete","Book", new { id = book.Id })
							</h5>
							<hr />
						}
					}
				</td>
				<td>
					@Html.ActionLink("Add Book", "Create","Book", new { id = item.Id }) |
					@Html.ActionLink("Delete", "Delete", new { id = item.Id })
				</td>
				<hr />
			</tr>
		}
	</tbody>
</table>
<script>
	function closeError() {
		document.getElementById("error").style.display = "none";
	}
</script>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library">Library</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library/Views/Shelf/Create.cshtml
@model Library.ViewModel.ShelfVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ShelfVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="LibaryId" class="control-label"></label>
                <input asp-for="LibaryId" class="form-control" />
                <span asp-validation-for="LibaryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Shelf/Details.cshtml
@model Library.Models.ShelfModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ShelfModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LibraryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LibraryId)
        </dd>
        @foreach (var set in Model.Sets)
        {
            @if (set != null)
            {
                <h5>Shelf</h5>
                <h5>Name: @set.Name </h5>
            }
        }
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Library/Views/Shelf/Index.cshtml
@model IEnumerable<Library.Models.ShelfModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Shelves</h1>
<p>
    @Html.ActionLink("Create New", "Create", "Shelf", new { id = ViewBag.Id })
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Height
            </th>
            <th>
                Width
            </th>
            <th>
                LibraryId
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LibraryId)
            </td>
            <td>
                @Html.ActionLink("set", "Index", "set", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { shelfid = item.Id, libraryid = ViewBag.Id })
            </td>
        </tr>
}
    </tbody>
</table>